
<table width="100%" border="0" cellspacing="3" cellpadding="0">
  <tr> 
    <td align="center"> 
      <hr width="95%">
      <font size="2">Copyright&copy; Korea EHT All rights reserved
      </font></td>
  </tr>
  <tr>
    <td align="center"><font size="2">주소 : 서울 금천구 가산동 493 대륭테크노타운 5차 307호(우편번호: 153-023)  
                                      <br>
                                     연락처 : (TEL) 02-2107-7610 (FAX) 02-2107-7619  
                                      <br> 
                E-mail : koreaeht@koreaeht.com  
         </font>
       </td>
  </tr>
</table>
