<table width="650" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><p><strong>SECT - Skin effect trace heating</strong></p></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="222" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><img src="images/sect_img01.jpg"></td>
          </tr>
        </table></td>
        <td width="15">&nbsp;</td>
        <td valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>¤ýFor temperature maintenance up to 150¡É<br>
¤ýFor very long pipes (up to 25§°) with only 1 supply connection<br>
¤ýTechnology applicable to elevated, buried, or immersed pipes<br>
¤ýVoltage up 2500 VAC<br>
¤ýHigh robustness (polyfluored insulation jacket is heat, corrosion, rending, corona effect resistant / cables protected by steel tube)<br>
¤ýNo maintenance and possible exchange of cable without removing of insulation<br>
¤ýNo residual voltage on external face of tube and pipe / Earth connected / No effect on cathodic protective device<br>
¤ýLow temperature gap betwen cable, tube, and pipe</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>¤ýThe pipe being maintained at temperature is fitted with one or several small steel tubes set on pipe generants by welding or by rings<br>
¤ýA non heating cable, set inside the tube, conduct the voltage up to the end of the pipe<br>
¤ýThe return of current goes by the small tube, but only through an internal thickness defined by the laws of kelvin and Maxwell<br>
¤ýThe internal face, and so, the pipe itself, remains without residual voltage and can be earth connected<br>
¤ýthe heating of the small tube is generated by joules effect in its thin intenal thickness concerned, and transfers it ti the pipe by conduction(welding/rings/thermal cement)</td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td><p>&nbsp;</p></td>
  </tr>
  <tr>
    <td><img src="images/sect_img02.gif"></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><img src="images/sect_img03.gif"></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="290"><img src="images/sect_img04.gif"></td>
        <td width="15">&nbsp;</td>
        <td valign="top">Depending on heating power needed and pipeline length, SKIN SYSTEM may consist of one, two or three (as is shown on the figure) heating elements.</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><strong>Control system</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>For enhancement of efficiency SECT System is equipped with control system that reduces power output in response to ambient temperature increase. That ensures reliable control of heating system status and emergency conditions.</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="290"><img src="images/sect_img05.gif"></td>
        <td width="15">&nbsp;</td>
        <td valign="top">Calculated temperature distribution<br>
          <br>
          An example of heating heat-insulated pipeline by three SECT system heating elements with total power output 130 W/m. <br>
          Pipe diameter 530 mm, ambient air temperature -20&deg;C.</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="290"><img src="images/sect_img06.gif"></td>
        <td width="15">&nbsp;</td>
        <td valign="top"><p>Temperature range of calculation<br>
          -40 &ndash; +200&deg;C</p>
          <p>Power supply:<br>
            up to 3 kVAC 50 Hz</p>
          <p>Construction:<br>
            Heat-generating element &mdash; tube of low-carbon steel 20&ndash;60 mm in diameter with 2-4 mm wall thickness</p>
          <p>Current carrying conductor &ndash; Special conductor<br>
            resistive to high voltage (up to 3 kV), high temperature (up to 200&deg;C) and mechanical stress at installation</p>
          <p>Anticorrosive insulation of heating element &mdash; Epoxy coating(on customer's request)</p></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><p><strong>SECT system efficiency in comparison with other heater types </strong></p></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><img src="images/sect_img07.gif"></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><strong>Accessories</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><p>Full range of accessories is available including distribution, connecting and terminal boxes and couplings, fastenings and control units (controllers and control cabinets).</p></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><strong>SECT System Diagram</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><img src="images/sect_img08.gif"></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><p><strong>Commercial proposal</strong></p></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&gt; SEHMS General technical description</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><p>Summary description of SEHMS</p>      </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Pipeline electrical heating system in which unique technique is realized using skin-effect physical phenomenon (hereafter referred as SEHMS) is designed for heating of long and extra long pipelines 
      including buried ones as in the given project. SEHMS is the only industrial heating system being a costeffective method of heat tracing of long and extra long pipelines to ensure normal flow of the product.<br>
      In the SEHMS special heating elements are applied, which use SKIN-effect and proximity effect in ferromagnetic conductors at alternative power current.<br>
    The heating element is a low carbon steel tube with the wall thickness not less than 3mm, inside of which a non-magnetic conductor (copper) is placed. At the end of the run the conductor is connected to      a steel pipe, and at the beginning of the run alternating voltage is being applied between the pipe and the conductor. The voltage value is calculated taking into account the heat generation required and the    length of the heated segment.</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td align="center"><img src="images/sect_img09.gif"></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Alternative current runs through the whole inner conductor section. No significant surface effect arises      in nonmagnetic material with good conductivity. In the outer ferromagnetic conductor (steel pipe) the      SKIN-effect is clear cut and the whole current runs through the internal pipe layer with about 1mm      thickness. The potential of external surface of pipe keeps on being virtually zero. Due to light thickness      of the SKIN-layer, basic heat generating (up to 80%) is being performed in the steel pipe. At the      beginning and at the end of the circuit (heating pipe segment) the outer surface of the SKIN-tube is    reliably grounded what ensures additional safety of the SEHMS system.</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>SEHMS advantages</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Minimum quantity of heating elements power supply points. According to the designing experience      of these systems, the maximum length of ONE LINE of SEHMS may be up to 10 000m. By boosting      two segments of the line from one point, the distance between power supply points may be up to      20 000m.<br>
      Less investment costs against other heat tracing systems. That is supported by the fact that in      SEHMS SKIN-cable of a big section is discharged from heat generating and in fact performs the      function of an integrated covering power network.<br>
      Electrical safety. The external surface of heating element (tube) has a zero potential against earth, it is      grounded and shields and protects completely the current-carrying conductor located inside.<br>
      Good thermal contact. Metal heat generating element (tube) is welded directly to the main pipeline or      is tightly attached to it by using special elements. For improved heat transfer a special heat conductive      paste is applied.<br>
    Reliability. Strong heat generating elements in form of steel tubes provide mechanical strength and      protection of current-carrying conductors from damage. Heat generating elements do not have outer    insulation, which can be damaged while installing.</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&gt; Basic engineering data</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Case 1&gt; HUCHEMS area 5Km project</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>1-1. Input data and Technical requirements</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>The current project includes the construction of a 6&rdquo; MNB pipeline, insulated with 10mm aerogel      (conductivity: 0.014 W/m&middot;oC, ambient temp 10oC) heated to a max temp. of 22 &deg;C. Temperature in      empty pipe or stagnant product shall be maintained at 20 &deg;C.<br>
      The heater element will be installed in one 27 mm carbon steel tube, strapped every 30 cm along      the length, located at 45o of the vertical at the bottom of the pipe.<br>
      The output heat in the heat tubes should make up 27 watts/meter for the section to maintain a      pipeline temp of 20 &deg;C.<br>
      The SKIN-EFFECT system will consist of one heating section. Power feeding will be carried out in      one place at the end of the pipeline.<br>
    Electric cubicles should be of the indoor metal enclosed and should contain all electrical protective,    indicating and operating devices including sequential control and fault indicators.</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>1-2. Heat engineering calculations</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>According to BS 6351, calculation of heat loss from the pipeline surface is being performed      according to the following formula:<br>
      <br>
      P=(2&pi;&lambda;*&Delta;T&times;l)/ln(d2/d1)<br>
      <br>
      where:<br>
      P &ndash; power loss intensity, W,<br>
      &lambda; - effective heat conductivity factor, W/m&middot;&deg;K,<br>
      &Delta;T &ndash; temperature difference between the heated surface and the ambient air, K,<br>
      d2 &ndash; outer diameter of the thermal insulation, m,<br>
      d1 &ndash; inner diameter of the thermal insulation, m,<br>
    l &ndash; length, m.</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><table width="100%" border="1" cellspacing="0" cellpadding="3" bordercolor="#CCCCCC" style="border-collapse: collapse">
      <tr>
        <td rowspan="2" align="center">No</td>
        <td rowspan="2" align="center">Pipeline<br>
          designation</td>
        <td rowspan="2" align="center">Diameter,<br>
          Inches</td>
        <td rowspan="2" align="center">Length,<br>
          m</td>
        <td rowspan="2" align="center">Insulation<br>
          thickness, §®</td>
        <td colspan="2" align="center">Thermal specifications, ¡É</td>
        <td rowspan="2" align="center">Account<br>
          safety factor</td>
        <td rowspan="2" align="center">Conculated          <br>
          Linear heat loss, <br>
          W/m</td>
      </tr>
      <tr>
        <td align="center">Required for<br>
          product</td>
        <td align="center">Ambient,<br>
          min</td>
        </tr>
      <tr>
        <td align="center">1</td>
        <td align="center">mono nitro Benzene</td>
        <td align="center">6</td>
        <td align="center">5000.00</td>
        <td align="center">10</td>
        <td align="center">20</td>
        <td align="center">-10</td>
        <td align="center">1,2</td>
        <td align="center">27</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Technical solution</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>According to performed calculation the electrical heating system meets your technical requirements      and can be realized by installation of one induction-resistive heater along the pipeline, having linear      output 27 W/m    Powering of the electrical heating system is realized in one place.</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  
</table>
